name: Test Blog Post Workflow
on:
  workflow_dispatch: # 수동 실행만 가능

jobs:
  test-blog-update:
    name: Test README update with blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://nullisdefined.site/feed.xml"
          max_post_count: 5
          template: "- [$title]($url)"
          commit_message: "Updated with latest blog posts"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
